### ISSUE TITLE
你们好！

### ISSUE THREAD

**Issue by H2ydrogen** [LvPeng990324/performance_management#1]
嗨~你们好
我是一个大二的学生，寒假开始学习django，目前应该只有入门水平
很巧的是我也正在试着搭建一个企业的绩效管理系统，目前已经基本完成了后台的主要逻辑代码
但是对于项目和django还有很多地方有疑问，我很急切地想要学习和解决
看到你们感觉看到了志同道合的小伙伴，希望能和你们取得联系。
如果有能力的话，我也愿意帮助你们完成这个项目。
不知道怎么联系你们，于是就在此写下了这条issue
以下是我的联系方式：
qq1175328080
wechet 13258393975
如有打扰，请多包涵

**Comment by LvPeng990324** [comment]
谢谢你的认可，我稍后会加你QQ

**Comment by LvPeng990324** [comment]
你的QQ需要认证，我的Q:1365907110    wechat：lp1365907110
