### ISSUE TITLE
项目启动相关问题

### ISSUE THREAD

**Issue by mayufeng2595** [LvPeng990324/performance_management#2]
你好，我在github上搜索到您的项目之后想启动一下看看效果，但是启动后发现输入  http://xxxx/ 之后，zhe li这里我在nginx上把端口设置成了80，页面展示如下：
![image](https://user-images.githubusercontent.com/25172219/86528043-13f08f80-bed7-11ea-894b-2e70e030c54e.png)

不知道是什么原因导致的，我现在用的是python2 的环境

**Comment by LvPeng990324** [comment]
它是python3.6+Django2.2开发的

**Comment by mayufeng2595** [comment]
谢谢，我再试试。

**Comment by mayufeng2595** [comment]
请问 postgreSql 有版本要求吗？

**Comment by LvPeng990324** [comment]
> 请问 postgreSql 有版本要求吗？

用PostgreSQL11.5开发的，也用mysql5.7调试过，使用Django的话，数据库理论上是都兼容的，不过如果你想更稳一些的话，可以用PostgreSQL11.5

**Comment by mayufeng2595** [comment]
👌万分感谢

**Comment by LvPeng990324** [comment]
> 👌万分感谢

不客气，如果没有后续问题的话，12:00后我会关闭这个issue

**Comment by mayufeng2595** [comment]
暂时没有问题了
