### ISSUE TITLE
数据初始化问题

### ISSUE THREAD

**Issue by mayufeng2595** [LvPeng990324/performance_management#3]
你好，我这边在系统初始化的时候，报错，django_content_type 这个表找不到，请问表的结构需要提前创建好嘛？
以下是报错内容：
![image](https://user-images.githubusercontent.com/25172219/86580182-f3950380-bfb0-11ea-89e6-79d0c1335862.png)

**Comment by LvPeng990324** [comment]
> 你好，我这边在系统初始化的时候，报错，django_content_type 这个表找不到，请问表的结构需要提前创建好嘛？
> 以下是报错内容：
> ![image](https://user-images.githubusercontent.com/25172219/86580182-f3950380-bfb0-11ea-89e6-79d0c1335862.png)

你有没有运行`python manage.py migrate`这条命令来执行第一次数据库迁移动作？

**Comment by mayufeng2595** [comment]
是的，没有做这个操作。现在已经可以了，服务已经启动了，谢谢🙏

**Comment by LvPeng990324** [comment]
> 是的，没有做这个操作。现在已经可以了，服务已经启动了，谢谢🙏

不客气，
